services:
    postgres:
        image: postgres
        container_name: postgres_container
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: super1234password
            POSTGRES_DB: database
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@email.com
            PGADMIN_DEFAULT_PASSWORD: admin@krasavchik
            PGADMIN_LISTEN_PORT: 8080
            PGADMIN_SERVER_PORT: 5432
            PGADMIN_SERVER_NAME: PostgreSQL
        ports:
            - "8080:8080"
        depends_on:
            - postgres
